---
spring:
  profiles: eureka
server:  
  ssl:
    enabled: true
    key-store: /Users/chris/EclipseProjects/sample-spring-microservices/ssl/keystore2
    key-store-password: password
    keyAlias: tomcat
    trust-store: /Users/chris/EclipseProjects/sample-spring-microservices/ssl/truststore2
    trust-store-password: password

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    securePortEnabled: true
    securePort: ${server.port}
    # hostname: localhost
    # homePageUrl: https://${eureka.instance.hostname}:${server.port}/
          
ribbon:
  isSecured: true
  eureka:
    enabled: true
---