server:  
  port: ${PORT:8761}
  ssl:
    enabled: true
    key-store: /Users/chris/EclipseProjects/sample-spring-microservices/ssl/keystore2
    key-store-password: password
    keyAlias: tomcat
    trust-store: /Users/chris/EclipseProjects/sample-spring-microservices/ssl/truststore2
    trust-store-password: password
    
eureka:  
  instance:
    hostname: localhost
    securePort: ${server.port}
    securePortEnabled: true
    secureVirtualHostName: ${spring.application.name}
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    # statusPageUrl: https://${eureka.instance.hostname}:${server.port}/admin/info
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0