---
spring:  
  application:
    name: account-service
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
      
server:  
  port: ${PORT:2222}
security:
  oauth2:
    client:
      clientId: openamoauth2
      clientSecret: password
      accessTokenUri: https://ubuntu.chris.com:8443/openam/oauth2/access_token
      userAuthorizationUri: https://ubuntu.chris.com:8443/openam/oauth2/authorize
      # redirectUri: http://localhost:8080/user
      tokenName: access_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: mail cn
    resource:
      userInfoUri: http://ubuntu.chris.com:8080/openam/oauth2/tokeninfo
      preferTokenInfo: false
---