---

spring:
  profiles: standalone
  cloud:
    discovery:
      enabled: false
    security:
      enabled: false
  security:
    basic:
      enabled: false
  management:
    security:
      enabled: false
---